### ISSUE TITLE
Monday - Final Actions

### ISSUE THREAD

**Issue by KelvenH** [tindyc/valentime#64]
Testing;
- continue responsive review
- lighthouse
- html / css validators / JShint
- user stories

Check code;
- remove unused css classes / js console logs

README;
- testing outputs
- outstanding bugs (e.g. facebook share icon)
- future features (Kanban suggestions)

**Comment by kera-cudmore** [comment]
OK Guys so am going to just list below everything that I can see that might need fine tuning/changing - and we'll see how many we can get through tomorrow 😊

- Responsive image - to be added to the hackathon page, in meta of all pages(incl. alt description) and the readme (Kera)
- Footer - is there any way to align the team name so it sits in the centre of the footer
- card-image - I think needs to be either cover or contain - seems to be doing a bit of both depending on screen size on some pages
- can we change to a toggle nav bar on tablet size? the writing is a little squashed

README
- Wireframes to be added to the readme (Pratima)
- Testing


HOME PAGE
- cooking card is not redirecting to the page (all other links are ☑️)
- possibly change the home page blurb to what is in top of readme - gives bit more info about the site?
- media 600px - need to adjust card-text to be 1.75rem

MOVIES PAGE
- .footer-project-name needs to be added to the valentime in footer
- all nav links and footer links work ✅
- have tried to test as many cards external links as possible - the ones I have checked are opening fine in separate window. Sometimes a card is coming up a few times in a row, guessing thats because its random
- media 600px - need to adjust card-text to be 1.75rem -  - maybe also adjust for tablet too 

FOOD & DRINK PAGE
- .footer-project-name needs to be added to the valentime in footer
- Links all look ✅ again sometimes cards seem to repeat for 2-3 clicks then move on
- media 600px - need to adjust card-text to be 1.75rem -  - maybe also adjust for tablet too 

GAMES PAGE
- .footer-project-name needs to be added to the valentime in footer
- change images so that they are all same size
- if we have time maybe find some other images to throw on the back?
- cards flip and the ones I managed to check seem ✅ opening in new window
- all other links on page working fine ✅
- media 600px - need to adjust card-text to be 1.75rem - maybe also adjust for tablet too 

CONTACT US PAGE
- can we change page header to be consistent with all other pages
- all links working ✅
-the team images need to be made smaller for tablets and phones
- add spacing between form inputs - screens smaller than 768px
- if possible move the subscribe box so it isn't covering content


404 PAGE
- seems like there is now an issue with the footer/image - will need to be looked at 
- the heart interactive is still in footer - needs to be moved into nav
- all nav links working ✅

CSS
- This is probably going to need going through and seeing if anything needs to be moved/deleted (I did spot a commented out section in the contact us part)
- when ran through validator tonight the css passed✅
<img width="1506" alt="Screenshot 2022-02-28 at 01 12 45" src="https://user-images.githubusercontent.com/92253071/155908984-5cdf89a5-779e-455e-979c-c03b49163f17.png">
 
W3C VALIDATOR
index ✅
<img width="1506" alt="Screenshot 2022-02-28 at 01 10 49" src="https://user-images.githubusercontent.com/92253071/155909034-595d408a-0838-4a5d-9d12-cc54c9495dee.png">

<img width="1506" alt="Screenshot 2022-02-28 at 01 10 27" src="https://user-images.githubusercontent.com/92253071/155909036-f4c5be3e-e533-4c0e-be93-c98550dbc70d.png">

<img width="1506" alt="Screenshot 2022-02-28 at 01 10 02" src="https://user-images.githubusercontent.com/92253071/155909038-60d153c0-dab8-47b1-a61a-6d303afe718e.png">

<img width="1506" alt="Screenshot 2022-02-28 at 01 09 50" src="https://user-images.githubusercontent.com/92253071/155909039-222735dd-2bc7-4c76-a024-6835af5be1e6.png">

<img width="1506" alt="Screenshot 2022-02-28 at 01 09 29" src="https://user-images.githubusercontent.com/92253071/155909040-0332f035-835c-4fe8-9d94-da0307a2332a.png">

<img width="1506" alt="Screenshot 2022-02-28 at 01 08 58" src="https://user-
images.githubusercontent.com/92253071/155909042-0297e792-6242-4fe5-b1c4-aa81b9f8f2a6.png">


LIGHTHOUSE
- index page - all green ✅
- movies - accessibility orange, rest green
- food - accessibility orange, rest green
- games - accessibility orange, rest green
- contact - accessibility orange, rest green
- 404 - accessibility & seo orange, rest green



Well done if you made it this far - It looks worse than it is - I did tell you all I love a list!

**Comment by kera-cudmore** [comment]
One last thing - just checked quick and on mobile the cards are over the blurb text - so will need to add a bit of padding and could possibly make card width a bit smaller too

![Uploading F8C44A0B-86B0-4EEA-BA08-736A28D5D260.png…]()

**Comment by kera-cudmore** [comment]
Also do we need to delete the category template page?
